// Generated by gencpp from file ai_robotics_lab/FFSolveResponse.msg
// DO NOT EDIT!


#ifndef AI_ROBOTICS_LAB_MESSAGE_FFSOLVERESPONSE_H
#define AI_ROBOTICS_LAB_MESSAGE_FFSOLVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ai_robotics_lab
{
template <class ContainerAllocator>
struct FFSolveResponse_
{
  typedef FFSolveResponse_<ContainerAllocator> Type;

  FFSolveResponse_()
    : solution()  {
    }
  FFSolveResponse_(const ContainerAllocator& _alloc)
    : solution(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _solution_type;
  _solution_type solution;





  typedef boost::shared_ptr< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FFSolveResponse_

typedef ::ai_robotics_lab::FFSolveResponse_<std::allocator<void> > FFSolveResponse;

typedef boost::shared_ptr< ::ai_robotics_lab::FFSolveResponse > FFSolveResponsePtr;
typedef boost::shared_ptr< ::ai_robotics_lab::FFSolveResponse const> FFSolveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator1> & lhs, const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.solution == rhs.solution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator1> & lhs, const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ai_robotics_lab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf4c8455c11ed8d4780c2f56f64948d0";
  }

  static const char* value(const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf4c8455c11ed8d4ULL;
  static const uint64_t static_value2 = 0x780c2f56f64948d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ai_robotics_lab/FFSolveResponse";
  }

  static const char* value(const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string solution\n"
"\n"
;
  }

  static const char* value(const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FFSolveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ai_robotics_lab::FFSolveResponse_<ContainerAllocator>& v)
  {
    s << indent << "solution: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.solution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AI_ROBOTICS_LAB_MESSAGE_FFSOLVERESPONSE_H
